export const SITE = {
  website: "https://fruizg0302.github.io/",
  author: "Fernando Ruiz",
  profile: "https://github.com/fruizg0302",
  desc: "Personal blog by Fernando Ruiz. Software engineering, Ruby, AI, and more.",
  title: "Fernando Ruiz",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "America/Chicago",
} as const;
